"""empty message

Revision ID: 47f54ccdff6a
Revises: bd22588c94bc
Create Date: 2019-11-07 18:21:30.271962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f54ccdff6a'
down_revision = 'bd22588c94bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('remind_offset', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'remind_offset')
    # ### end Alembic commands ###
