"""empty message

Revision ID: 73d82e1f5cef
Revises: fd70381c7dfc
Create Date: 2019-11-06 23:05:51.702279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d82e1f5cef'
down_revision = 'fd70381c7dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('remind', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('remind_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'remind_date')
    op.drop_column('users', 'remind')
    # ### end Alembic commands ###
