"""empty message

Revision ID: f2bd9df0d340
Revises: 7f63616951c8
Create Date: 2020-03-15 23:02:30.864190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2bd9df0d340'
down_revision = '7f63616951c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dinamic_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_name', sa.String(), nullable=True),
    sa.Column('dinamic_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dinamic_items')
    # ### end Alembic commands ###
