"""empty message

Revision ID: a527015c4a64
Revises: e71595768ac1
Create Date: 2019-11-07 19:44:21.341087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a527015c4a64'
down_revision = 'e71595768ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('remind_offset', sa.Integer()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'remind_offset')
    # ### end Alembic commands ###
