"""empty message

Revision ID: dcc1c3e4e1ab
Revises: 
Create Date: 2019-10-16 17:36:52.175131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc1c3e4e1ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('cabinet', sa.String(), nullable=True))
    op.add_column('users', sa.Column('group_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'group_name')
    op.drop_column('subject', 'cabinet')
    # ### end Alembic commands ###
